/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_img_processing_ImgJni */

#ifndef _Included_org_img_processing_ImgJni
#define _Included_org_img_processing_ImgJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_img_processing_ImgJni
 * Method:    processing
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_img_processing_ImgJni_processing
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
